services:
  dev:
    build:
      context: .
      target: dev
    image: localhost/vhdl-fmt-dev:latest
    volumes:
      - .:/app:z
      - conan-cache:/root/.conan2
    command: ["/bin/bash"]
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

volumes:
  conan-cache:
